apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: sepsisai
spec:
  # ClusterIP — only reachable inside the cluster
  selector:
    app: mongodb
  ports:
    - port: 27017
      targetPort: 27017
